### ISSUE TITLE
Cant connect to DB

### ISSUE THREAD

**Issue by AbieReifer** [adadgio/neo4j-js-ng2#12]
I got the front end of the application to build and it appears to run in the bowser. But it doesnt seem to connect to the Neo4j instance running.  (Top righthand corner says Neo4J OFFLINE in red)
 The neo4j.setting.json  file in the client section has the following included in it  (I've replaced my actual password with MyPassword for the purposes of this posting)

"authBasic": "Basic: neo4j:MyPassword"

I have also tried it set as follows 

"authBasic": "Basic: <neo4j:MyPassword>"

Neither seems to work. 

I am able to connect tot the DB with those credentials in other apps using the BOLT interface. So I know the crednetials I have work.

Any suggestions?

Thanks,

Abie

**Comment by JavascriptMick** [comment]
pretty sure the documentation says you gotta base 64 encode the username:password string and use that instead.  on mac you can put your username:password into a file called in.txt and then use this...
openssl base64 -in in.txt -out out.txt
But having said that... I can't get it to connect either

**Comment by adadgio** [comment]
Hi guys, the docs indeed state this. I usually use a tool like http://www.utilities-online.info/base64 to test it. This should work (aka `user:password`)

![image](https://user-images.githubusercontent.com/502070/40491534-9ff8e3bc-5f6e-11e8-966e-e91cd819c18f.png)

And settings json would look like: `"authBasic": "Basic Ym9iOm1hcmxleQ=="` in this case.

If it doesn't its probably some problem on your neo4j HTTP API because connection is pretty straightforward.

Could **one of you guys post** the image/content of the browser console loggings / network requests  here please ?

**Comment by AbieReifer** [comment]
Adadgio -Wow - that worked. Thanks so much!!

One more related question - I am beginning to work in Angular (6) - but when I compile this using 6 it throws all kinds of errors - I think because its written in Angular 2. Is there a way I can compile this for Angualr 6 and have it work?

**Comment by adadgio** [comment]
Hm not sure, its probably the angular CLI versions (local/global). What kind of errors
This probably wont belong here as an issue though...
